Set up encrypted swap

diff --git a/arch-install b/arch-install
--- a/arch-install
+++ b/arch-install
@@ -18,14 +18,21 @@ if [[ $device == *nvme* ]]; then
 fi
 
 boot_partition=${device}${extra}1
-root_partition=${device}${extra}2
+swap_partition_raw=${device}${extra}2
+swap_partition_id=$(find -L /dev/disk/by-id -samefile "$swap_partition_raw" | head -1)
+root_partition=${device}${extra}3
+
+if ! [[ $swap_partition_id ]]; then
+    echo "Cannot get swap partition ID for $swap_partition_raw" >&2
+    exit 1
+fi
 
 sgdisk -Z "$device"
-sgdisk -n 1:0:512M "$device"
-sgdisk -t 1:ef00 "$device"  # part type to ESP
-sgdisk -c 1:ESP "$device"
-sgdisk -N 2 "$device"
-sgdisk -c 2:Root "$device"
+
+sgdisk -n 0:0:+512M -t 1:ef00 -c 1:ESP "$device"
+sgdisk -n 0:0:+1G -t 1:8200 -c 1:Swap "$device"
+sgdisk -n 0:0:0 -c 3:Root "$device"
+
 mkfs.msdos -F32 -n "$short_hostname"-/boot "$boot_partition"
 
 mountpoint=$(mktemp -d)
@@ -53,9 +60,14 @@ pacstrap "$mountpoint" base base-devel git ansible
 
 cp /etc/pacman.d/mirrorlist "$mountpoint"/etc/pacman.d/mirrorlist
 
+cat > "$mountpoint"/etc/crypttab << EOF
+swap $swap_partition_id /dev/urandom swap,cipher=aes-xts-plain64,size=256
+EOF
+
 cat > "$mountpoint"/etc/fstab << EOF
 LABEL=$short_hostname-/boot /boot vfat  defaults,noatime 0 1
 LABEL=$short_hostname-/     /     btrfs defaults,noatime,compress=zstd 0 1
+/dev/mapper/swap            none  swap  defaults 0 0
 EOF
 
 echo "$hostname" > "$mountpoint"/etc/hostname
